var view = pannellum.viewer("panorama", {
  default: {
    firstScene: "gateout",
    sceneFadeDuration: 1000,
    autoLoad: true,
    disableKeyboardCtrl: true,
  },
  scenes: {
    //campus grounds
    buildingB: {
      title: "Building B",
      pitch: 12,
      yaw: -13,
      hfov: 120,
      type: "equirectangular",
      panorama: "Capstone/Outside/buildingb.jpg",
      hotSpots: [
        {
          pitch: -9,
          yaw: 167,
          type: "scene",
          text: "Waiting Area",
          sceneId: "gwaiting",
        },
        {
          pitch: -3,
          yaw: 78,
          type: "scene",
          text: "Infirmary",
          sceneId: "infirmary",
        },
        {
          pitch: -0,
          yaw: 76,
          hfov: 100,
          type: "scene",
          text: "Building C",
          sceneId: "buildingC",
        },
        {
          pitch: -5,
          yaw: -108,
          hfov: 100,
          type: "scene",
          text: "Building A",
          sceneId: "buildingA",
        },
        {
          pitch: 0,
          yaw: -29,
          hfov: 115,
          type: "info",
          text: "Registrar",
        },
        {
          pitch: -1,
          yaw: -3,
          hfov: 120,
          type: "scene",
          text: "Building B Hall",
          sceneId: "bhall",
        },
      ],
    },

    gwaitng: {
      title: "Waiting Area",
      hfov: 120,
      yaw: 5,
      type: "equirectangular",
      panorama: "Capstone/Outside/waitingarea.jpg",
      hotSpots: [
        {
          pitch: -4,
          yaw: -111,
          hfov: 120,
          type: "scene",
          text: "Building B",
          sceneId: "buildingB",
        },
        {
          pitch: -3,
          yaw: 160,
          hfov: 110,
          type: "scene",
          text: "Building A",
          sceneId: "buildingA",
        },
        {
          pitch: 0,
          yaw: 5,
          hfov: 110,
          type: "scene",
          text: "Activity Center",
          sceneId: "court",
        },
      ],
    },
    buildingC: {
      title: "Building C",
      hfov: 110,
      yaw: 5,
      type: "equirectangular",
      hfov: 120,
      panorama: "Capstone/Outside/buildingc.jpg",
      hotSpots: [
        {
          pitch: -6,
          yaw: -146,
          hfov: 120,
          type: "scene",
          text: "Activity Center",
          sceneId: "court",
        },
        {
          pitch: -4,
          yaw: -123,
          hfov: 120,
          type: "scene",
          text: "Infirmary",
          sceneId: "infirmary",
        },
      ],
    },
    buildingA: {
      title: "Building A",
      type: "equirectangular",
      hfov: 120,
      panorama: "Capstone/Outside/buildinga.jpg",
      hotSpots: [
        {
          pitch: 0,
          yaw: 150,
          hfov: 100,
          type: "scene",
          text: "Waiting Area",
          sceneId: "gwaitng",
        },
        {
          pitch: -10,
          yaw: -88,
          hfov: 100,
          type: "scene",
          text: "Gate",
          sceneId: "gatein",
        },
        {
          pitch: 5,
          yaw: 112,
          hfov: 100,
          type: "scene",
          text: "Building B",
          sceneId: "buildingB",
        },
        {
          pitch: -16,
          yaw: -91,
          hfov: 100,
          type: "scene",
          text: "Building E",
          sceneId: "buildingE",
        },
        {
          pitch: -2,
          yaw: 17,
          hfov: 100,
          type: "scene",
          text: "Building A Hall",
          sceneId: "ahall",
        },
      ],
    },
    gatein: {
      title: "Gate",
      type: "equirectangular",
      horizonRoll: 3,
      hfov: 120,
      panorama: "Capstone/Outside/gatein.jpg",
      hotSpots: [
        {
          pitch: 4,
          yaw: 132,
          hfov: 100,
          type: "scene",
          text: "Building E",
          sceneId: "buildingE",
        },
        {
          pitch: -3,
          yaw: -1,
          hfov: 120,
          type: "scene",
          text: "Exit",
          sceneId: "gateout",
        },
      ],
    },
    court: {
      title: "Activity Center",
      type: "equirectangular",
      hfov: 120,
      panorama: "Capstone/Outside/court.jpg",
      hotSpots: [
        {
          pitch: -4,
          yaw: -85,
          hfov: 100,
          type: "Info",
          text: "Building B",
          sceneId: "buildingB",
        },
        {
          pitch: -0.5,
          yaw: 153,
          hfov: 100,
          type: "scene",
          text: "Waiting Area",
          sceneId: "gwaitng",
        },
        {
          pitch: -0.5,
          yaw: 153,
          hfov: 100,
          type: "scene",
          text: "Building D",
          sceneId: "buildingD",
        },
        {
          pitch: 3,
          yaw: 90,
          hfov: 100,
          type: "scene",
          text: "Building C",
          sceneId: "buildingC",
        },
      ],
    },
    buildingE: {
      title: "Building E",
      type: "equirectangular",
      hfov: 120,
      panorama: "../Capstone/Outside/buildinge.jpg",
      hotSpots: [
        {
          pitch: -1,
          yaw: -165,
          hfov: 100,
          type: "scene",
          text: "Building A",
          sceneId: "buildingA",
        },
        {
          pitch: -5,
          yaw: 17,
          hfov: 100,
          type: "scene",
          text: "Gate",
          sceneId: "gatein",
        },
        {
          pitch: -7,
          yaw: -67,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall",
        },
      ],
    },
    gateout: {
      title: "Entrance",
      type: "equirectangular",
      hfov: 120,
      panorama: "Capstone/Outside/gateout2.jpg",
      pitch: 25,
      yaw: -180,
      hfov: 120,
      hotSpots: [
        {
          pitch: -7,
          yaw: -176,
          hfov: 120,
          type: "scene",
          text: "Entrance",
          sceneId: "gatein",
        },
        {
          pitch: 1,
          yaw: 74,
          hfov: 100,
          type: "scene",
          text: "Waiting Shed",
          sceneId: "shed",
        },
      ],
    },
    shed: {
      title: "Waiting Shed",
      type: "equirectangular",
      hfov: 120,
      panorama: "Capstone/Outside/waiting shed.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 78,
          hfov: 100,
          type: "scene",
          text: "Entrance ",
          sceneId: "gateout",
        },
      ],
    },
    infirmary: {
      title: "Infirmary",
      type: "equirectangular",
      hfov: 120,
      panorama: "Capstone/Outside/infarmary.jpg",
      hotSpots: [
        {
          pitch: -5,
          yaw: -13,
          hfov: 100,
          type: "scene",
          text: "Building B",
          sceneId: "buildingB",
        },
        {
          pitch: -1,
          yaw: 167,
          hfov: 100,
          type: "scene",
          text: "Building C",
          sceneId: "buildingC",
        },
        {
          pitch: -3,
          yaw: -146,
          hfov: 100,
          type: "scene",
          text: "Activity Center",
          sceneId: "court",
        },
        {
          pitch: -9,
          yaw: -69,
          hfov: 100,
          type: "scene",
          text: "Infirmary",
          sceneId: "infirmaryin",
        },
      ],
    },
    infirmaryin: {
      title: "Waiting Shed",
      type: "equirectangular",
      hfov: 120,
      panorama: "Capstone/Outside/infirmaryIn.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 36,
          hfov: 100,
          type: "scene",
          text: "Exit",
          sceneId: "infirmary",
        },
      ],
    },
    buildingD: {
      title: "Building D",
      hfov: 120,
      type: "equirectangular",
      panorama: "Capstone/Outside/buildingd.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 36,
          hfov: 100,
          type: "scene",
          text: "Exit",
          sceneId: "infirmary",
        },
      ],
    },
    //end of campus grounds

    //building e rooms
    ehall: {
      title: "Building E Hall",
      type: "equirectangular",
      hfov: 120,
      horizonRoll: 4,
      panorama: "Capstone/e/e1/ehall2.jpg",
      hotSpots: [
        {
          pitch: -1,
          yaw: 93,
          hfov: 120,
          type: "scene",
          text: "Grounds",
          sceneId: "buildingE",
        },
        {
          pitch: -2,
          yaw: -177,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall2",
        },
        {
          pitch: -6,
          yaw: -167,
          hfov: 120,
          type: "scene",
          text: "Room 101",
          sceneId: "e101",
        },
        {
          pitch: -21,
          yaw: -45,
          hfov: 120,
          type: "scene",
          text: "Room 102",
          sceneId: "e102",
        },
        {
          pitch: -1,
          yaw: 1,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall3",
        },
        {
          pitch: -2,
          yaw: -7,
          hfov: 120,
          type: "scene",
          text: "Room 103",
          sceneId: "e103",
        },
      ],
    },
    ehall2: {
      title: "Building E Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -3,
      yaw: 174,
      horizonRoll: 2,
      panorama: "Capstone/e/e1/ehall1.jpg",
      hotSpots: [
        {
          pitch: -28,
          yaw: 124,
          hfov: 120,
          type: "scene",
          text: "Building E Second Floor",
          sceneId: "e2hall",
        },
        {
          pitch: -5,
          yaw: 168,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall",
        },
      ],
    },
    ehall3: {
      title: "Building E Hall",
      type: "equirectangular",
      hfov: 120,
      horizonRoll: 5,
      pitch: -3,
      yaw: 174,
      panorama: "Capstone/e/e1/ehall3.jpg",
      hotSpots: [
        {
          pitch: -10,
          yaw: -57,
          hfov: 120,
          type: "scene",
          text: "Building E Second Floor",
          sceneId: "e2hall",
        },
        {
          pitch: -3,
          yaw: 174,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall",
        },
        {
          pitch: -5,
          yaw: -174,
          hfov: 120,
          type: "scene",
          text: "Room 103",
          sceneId: "e103",
        },
      ],
    },
    e101: {
      title: "Room 101",
      type: "equirectangular",
      hfov: 120,
      pitch: -2,
      yaw: 35,
      horizonRoll: 2,
      panorama: "Capstone/e/e1/e101.jpg",
      hotSpots: [
        {
          pitch: -8,
          yaw: -13,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall",
        },
      ],
    },
    e102: {
      title: "Room 102",
      type: "equirectangular",
      hfov: 120,
      horizonRoll: 3,
      pitch: -2,
      yaw: -177,
      panorama: "Capstone/e/e1/e102.jpg",
      hotSpots: [
        {
          pitch: -10,
          yaw: 130,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall",
        },
      ],
    },
    e103: {
      title: "Room 103",
      type: "equirectangular",
      hfov: 120,
      pitch: -2,
      yaw: 166,
      horizonRoll: 1,
      panorama: "Capstone/e/e1/e103.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 116,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall",
        },
      ],
    },
    e2hall: {
      title: "Second Floor Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -4,
      yaw: -177,
      horizonRoll: 5,
      panorama: "Capstone/e/e2/e2hall2.jpg",
      hotSpots: [
        {
          pitch: -35,
          yaw: 71,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall2",
        },
        {
          pitch: -8,
          yaw: 177,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "e2hall2",
        },
        {
          pitch: -20,
          yaw: 127,
          hfov: 120,
          type: "scene",
          text: "Room 201",
          sceneId: "e201",
        },
      ],
    },
    e2hall2: {
      title: "Second Floor Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -6,
      yaw: 10,
      horizonRoll: 3,
      panorama: "Capstone/e/e2/e2hall3.jpg",
      hotSpots: [
        {
          pitch: -1,
          yaw: -157,
          hfov: 120,
          type: "scene",
          text: "Room 201",
          sceneId: "e201",
        },
        {
          pitch: -24,
          yaw: -37,
          hfov: 120,
          type: "scene",
          text: "Room 202",
          sceneId: "e202",
        },
        {
          pitch: -12,
          yaw: 11,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "e2hall3",
        },
        {
          pitch: -6,
          yaw: 3,
          hfov: 120,
          type: "scene",
          text: "Room 203",
          sceneId: "e203",
        },
      ],
    },
    e2hall3: {
      title: "Second Floor Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -2,
      yaw: -169,
      horizonRoll: 3,
      panorama: "Capstone/e/e2/e2hall4.jpg",
      hotSpots: [
        {
          pitch: -5,
          yaw: -160,
          hfov: 120,
          type: "scene",
          text: "Room 203",
          sceneId: "e203",
        },
        {
          pitch: -9,
          yaw: -169,
          hfov: 120,
          type: "scene",
          text: "Second Floor hall",
          sceneId: "e2hall",
        },
        {
          pitch: -41,
          yaw: -73,
          hfov: 120,
          type: "scene",
          text: "Building E Hall",
          sceneId: "ehall3",
        },
      ],
    },
    e201: {
      title: "Room 201",
      type: "equirectangular",
      hfov: 120,
      pitch: -9,
      yaw: -177,
      horizonRoll: 4,
      panorama: "Capstone/e/e2/e201.jpg",
      hotSpots: [
        {
          pitch: -11,
          yaw: 129,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "e2hall",
        },
      ],
    },
    e202: {
      title: "Room 202",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -171,
      horizonRoll: 4,
      panorama: "Capstone/e/e2/e202.jpg",
      hotSpots: [
        {
          pitch: -10,
          yaw: 134,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "e2hall2",
        },
      ],
    },
    e203: {
      title: "Room 203",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -171,

      panorama: "Capstone/e/e2/e203.jpg",
      hotSpots: [
        {
          pitch: -11,
          yaw: 137,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "e2hall3",
        },
      ],
    },
    //end of building e

    //building a rooms

    ahall: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -21,
      yaw: 173,
      horizonRoll: 3,
      panorama: "Capstone/a/a1/ahall.jpg",
      hotSpots: [
        {
          pitch: -23,
          yaw: 113,
          hfov: 120,
          type: "scene",
          text: "Student Council Office",
          sceneId: "council",
        },
        {
          pitch: -4,
          yaw: 109,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "a2hall",
        },
        {
          pitch: -6,
          yaw: 74,
          hfov: 120,
          type: "scene",
          text: "Mock Hotel Lab",
          sceneId: "ahotel",
        },
        {
          pitch: -20,
          yaw: 4,
          hfov: 120,
          type: "scene",
          text: "Grounds",
          sceneId: "buildingA",
        },
      ],
    },
    //building A second Floor
    a2hall: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -21,
      yaw: 173,
      horizonRoll: 3,
      panorama: "Capstone/a/a2/a2minihall.jpg",
      hotSpots: [
        {
          pitch: -33,
          yaw: 145,
          hfov: 120,
          type: "scene",
          text: "Third Floor Hall",
          sceneId: "a3hall",
        },
        {
          pitch: -5,
          yaw: 153,
          hfov: 120,
          type: "scene",
          text: "Building A Hall",
          sceneId: "ahall",
        },
        {
          pitch: -5,
          yaw: 170,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "a2hall2",
        },
      ],
    },
    a2hall2: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -12,
      yaw: 8,
      horizonRoll: 3,
      panorama: "Capstone/a/a2/a2hall.jpg",
      hotSpots: [
        {
          pitch: -2,
          yaw: -175,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "a2hall",
        },
        {
          pitch: -16,
          yaw: -150,
          hfov: 120,
          type: "scene",
          text: "Room 215",
          sceneId: "a215",
        },
        {
          pitch: -23,
          yaw: -133,
          hfov: 120,
          type: "scene",
          text: "Room 216",
          sceneId: "a216",
        },
        {
          pitch: -15,
          yaw: -11,
          hfov: 120,
          type: "scene",
          text: "Room 217",
          sceneId: "a217",
        },
      ],
    },
    a215: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -13,
      yaw: 2,
      horizonRoll: 3,
      panorama: "Capstone/a/a2/a215.jpg",
      hotSpots: [
        {
          pitch: -14,
          yaw: 56,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "a2hall2",
        },
      ],
    },
    a216: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -17,
      yaw: 179,
      horizonRoll: 3,
      panorama: "Capstone/a/a2/a216.jpg",
      hotSpots: [
        {
          pitch: -14,
          yaw: 117,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "a2hall2",
        },
      ],
    },
    a217: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -13,
      yaw: -45,
      horizonRoll: 3,
      panorama: "Capstone/a/a2/a217.jpg",
      hotSpots: [
        {
          pitch: -13,
          yaw: -107,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "a2hall2",
        },
      ],
    },
    //building A third Floor

    a3hall: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/a/a3/a3hall.jpg",
      hotSpots: [
        {
          pitch: -8,
          yaw: -176,
          hfov: 120,
          type: "scene",
          text: "Third Floor Hall",
          sceneId: "a3hall2",
        },
      ],
    },
    a3hall2: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/a/a3/a3hall2.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 26,
          hfov: 120,
          type: "scene",
          text: "Room 312",
          sceneId: "a312",
        },
        {
          pitch: -10,
          yaw: 165,
          hfov: 120,
          type: "scene",
          text: "Room 313",
          sceneId: "a313",
        },
      ],
    },
    a312: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/a/a3/a312A.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 26,
          hfov: 120,
          type: "scene",
          text: "Room 312",
          sceneId: "a312",
        },
      ],
    },
    a313: {
      title: "Building A Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/a/a3/a312B.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 26,
          hfov: 120,
          type: "scene",
          text: "Room 313",
          sceneId: "a313",
        },
      ],
    },
    //end of building a

    //building B
    bhall: {
      title: "Building B Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -4,
      yaw: 162,
      horizonRoll: 2,
      panorama: "Capstone/b/b1/bhallmid2.jpg",
      hotSpots: [
        {
          pitch: -2,
          yaw: 163,
          hfov: 120,
          type: "scene",
          text: "Building B Hall",
          sceneId: "bhall2",
        },
        {
          pitch: -7,
          yaw: -17,
          hfov: 120,
          type: "scene",
          text: "Building B Hall",
          sceneId: "bhall3",
        },
        {
          pitch: -5,
          yaw: -108,
          hfov: 120,
          type: "info",
          text: "Registrar",
          sceneId: "bhall3",
        },
        {
          pitch: -3,
          yaw: 31,
          hfov: 120,
          type: "scene",
          text: "Grounds",
          sceneId: "buildingB",
        },
      ],
    },
    bhall2: {
      title: "Building B Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/b/b1/bhallmid.jpg",
      hotSpots: [
        {
          pitch: -0,
          yaw: 10,
          hfov: 120,
          type: "scene",
          text: "Building B Hall",
          sceneId: "bhall",
        },
        {
          pitch: -5,
          yaw: -5,
          hfov: 120,
          type: "info",
          text: "Office",
          sceneId: "bhall",
        },
      ],
    },
    bhall3: {
      title: "Building B Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/b/b1/bhallmid3.jpg",
      hotSpots: [
        {
          pitch: -2,
          yaw: -9,
          hfov: 120,
          type: "scene",
          text: "Building B Hall",
          sceneId: "bhall4",
        },
        {
          pitch: -2,
          yaw: 172,
          hfov: 120,
          type: "scene",
          text: "Building B Hall",
          sceneId: "bhall",
        },
        {
          pitch: -20,
          yaw: -85,
          hfov: 120,
          type: "info",
          text: "Admin Office",
          sceneId: "bhall",
        },
        {
          pitch: -12,
          yaw: -42,
          hfov: 120,
          type: "info",
          text: "FMO Office",
          sceneId: "bhall",
        },
        {
          pitch: -1,
          yaw: -16,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "b2hall",
        },
      ],
    },
    bhall4: {
      title: "Building B Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/b/b1/bhallleft.jpg",
      hotSpots: [
        {
          pitch: -3,
          yaw: 4,
          hfov: 120,
          type: "scene",
          text: "Building B Hall",
          sceneId: "bhall3",
        },
      ],
    },
    b2hall: {
      title: "Second Floor Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -5,
      yaw: 8,
      horizonRoll: 3,
      panorama: "Capstone/b/b2/b2hall.jpg",
      hotSpots: [
        {
          pitch: -6,
          yaw: -176,
          hfov: 120,
          type: "scene",
          text: "Building B Hall",
          sceneId: "bhall3",
        },
        {
          pitch: -8,
          yaw: 176,
          hfov: 120,
          type: "scene",
          text: "Room 206",
          sceneId: "b206",
        },
        {
          pitch: -11,
          yaw: 170,
          hfov: 120,
          type: "scene",
          text: "Room 205",
          sceneId: "b205",
        },
        {
          pitch: -6,
          yaw: 19,
          hfov: 120,
          type: "scene",
          text: "Room 204",
          sceneId: "b204",
        },
        {
          pitch: 0,
          yaw: 8,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "b2hall2",
        },
        {
          pitch: 0,
          yaw: -176,
          hfov: 120,
          type: "scene",
          text: "Third Floor Hall",
          sceneId: "b3hall",
        },
      ],
    },
    b2hall2: {
      title: "Second Floor Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/b/b2/b2hallfac.jpg",
      hotSpots: [
        {
          pitch: -0,
          yaw: -174,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "b2hall",
        },
        {
          pitch: -3,
          yaw: 12,
          hfov: 120,
          type: "info",
          text: "Room 202",
          sceneId: "b202",
        },
        {
          pitch: -16,
          yaw: 62,
          hfov: 120,
          type: "info",
          text: "IT Faculty",
          sceneId: "b2hall",
        },
        {
          pitch: -32,
          yaw: 128,
          hfov: 120,
          type: "scene",
          text: "Room 203",
          sceneId: "b203",
        },
      ],
    },
    b206: {
      title: "Room 206",
      type: "equirectangular",
      hfov: 120,
      pitch: -10,
      yaw: -137,
      horizonRoll: 3,
      panorama: "Capstone/b/b2/b206.jpg",
      hotSpots: [
        {
          pitch: -10,
          yaw: 178,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "b2hall",
        },
      ],
    },
    b205: {
      title: "Room 205",
      type: "equirectangular",
      hfov: 120,
      pitch: -7,
      yaw: 5,
      horizonRoll: 3,
      panorama: "Capstone/b/b2/b205.jpg",
      hotSpots: [
        {
          pitch: -10,
          yaw: 178,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "b2hall",
        },
      ],
    },
    b204: {
      title: "Room 205",
      type: "equirectangular",
      hfov: 120,
      pitch: -3,
      yaw: -179,
      horizonRoll: 3,
      panorama: "Capstone/b/b2/b204.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 137,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "b2hall",
        },
      ],
    },
    b203: {
      title: "Room 203",
      type: "equirectangular",
      hfov: 120,
      pitch: -3,
      yaw: -179,
      horizonRoll: 5,
      panorama: "Capstone/b/b2/b203.jpg",
      hotSpots: [
        {
          pitch: -7,
          yaw: 140,
          hfov: 120,
          type: "scene",
          text: "Second Floor Hall",
          sceneId: "b2hall",
        },
      ],
    },
    b3hall: {
      title: "Third Floor Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/b/b3/b3hall.jpg",
      hotSpots: [
        {
          pitch: -5,
          yaw: -27,
          hfov: 120,
          type: "scene",
          text: "Room 306",
          sceneId: "b306",
        },
        {
          pitch: -33,
          yaw: -77,
          hfov: 120,
          type: "info",
          text: "MIS Office",
          sceneId: "b306",
        },
        {
          pitch: -27,
          yaw: -146,
          hfov: 120,
          type: "scene",
          text: "Room 304",
          sceneId: "b304",
        },
        {
          pitch: -1,
          yaw: 158,
          hfov: 120,
          type: "scene",
          text: "Third Floor Hall",
          sceneId: "b3hall2",
        },
      ],
    },
    b3hall2: {
      title: "Third Floor Hall",
      type: "equirectangular",
      hfov: 120,
      pitch: -8,
      yaw: -176,
      horizonRoll: 3,
      panorama: "Capstone/b/b3/b3hall2.jpg",
      hotSpots: [
        {
          pitch: -3,
          yaw: -3,
          hfov: 120,
          type: "scene",
          text: "Third Floor Hall",
          sceneId: "b3hall",
        },
        {
          pitch: -6,
          yaw: -170,
          hfov: 120,
          type: "info",
          text: "Library",
          sceneId: "b3hall",
        },
        {
          pitch: -15,
          yaw: -22,
          hfov: 120,
          type: "scene",
          text: "Room 301",
          sceneId: "b301",
        },
      ],
    },
    b306: {
      title: "Room 306",
      type: "equirectangular",
      hfov: 120,
      pitch: -11,
      yaw: -12,
      horizonRoll: 3,
      panorama: "Capstone/b/b3/b306.jpg",
      hotSpots: [
        {
          pitch: -10,
          yaw: 33,
          hfov: 120,
          type: "scene",
          text: "Third Floor Hall",
          sceneId: "b3hall",
        },
      ],
    },
    b304: {
      title: "Room 304",
      type: "equirectangular",
      hfov: 120,
      pitch: -6,
      yaw: 8,
      horizonRoll: 3,
      panorama: "../Capstone/b/b3/b304.jpg",
      hotSpots: [
        {
          pitch: -6,
          yaw: 53,
          hfov: 120,
          type: "scene",
          text: "Third Floor Hall",
          sceneId: "b3hall",
        },
      ],
    },
    b301: {
      title: "Room 301",
      type: "equirectangular",
      hfov: 120,
      pitch: -7,
      yaw: 20,
      horizonRoll: 3,
      panorama: "../Capstone/b/b3/b301.jpg",
      hotSpots: [
        {
          pitch: -4,
          yaw: 68,
          hfov: 120,
          type: "scene",
          text: "Third Floor Hall",
          sceneId: "b3hall",
        },
      ],
    },
  },
});

function loadscene(selectedscene) {
  view.loadScene(selectedscene);
}
